### ISSUE TITLE
Custom gateway example not working

### ISSUE THREAD

**Issue by igormukhingmailcom** [makasim/PayumBundleSandbox#57]
Hi.

I'm implementing my custom factory/actions for Liqpay and used Sandbox code as an example, but without success.

Having same error that I have on [web version](http://sandbox.payum.forma-dev.com) of Sandbox...

When I trying [custom gateway example](http://sandbox.payum.forma-dev.com/other/develop-payment-gateway-on-top-of-payum) - it redirects to `http://sandbox.payum.forma-dev.com/payment/capture/Kb-T1F3fxaZqAmsDRNfHTxuBSH1OJ09xEH8sQ4aPhcI` with exception `Request Capture{model: Identity} is not supported.`

That would be great if this example become working, so I can do my factory/actions based on this example.

Thanks.

PS Also looks like method [createPayment](https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/OtherExamplesBundle/Payum/FooBarGateway/FooBarGatewayPaymentFactory.php#L16) never called, because there is no code that call this method. Maybe it should be just `create` (if I understand [right](http://stackoverflow.com/questions/23992381/how-to-register-a-new-payum-payment-method-and-add-actions))?

**Comment by makasim** [comment]
fixed https://github.com/makasim/PayumBundleSandbox/commit/c8acbf0b7d96e2fb1bcef944e26c6e091dd588c3

The sandbox web could not be updated right now.

**Comment by igormukhingmailcom** [comment]
@makasim Thank you :)
