### ISSUE TITLE
Unrecognized options when installing your bundle

### ISSUE THREAD

**Issue by nicosomb** [makasim/PayumBundleSandbox#60]
Hello, 

I want to use PayumBundle, I tried to configured it as the documentation said but I had some problems. 
So I decided to try the sandbox, but I've the same errors: 

```
Unrecognized options "factory, username, password, signature, sandbox" under "payum.gateways.paypal_express_checkout_and_doctrine_orm"
``` 

Any idea?

**Comment by makasim** [comment]
What version of the sandbox you installed?

FYI the sandbox is meant as demo, you should not use it as a base of your project.

**Comment by nicosomb** [comment]
I use master branch. 

About sandbox/demo, I know that, I just want to see how the bundle works.

**Comment by makasim** [comment]
Could you please post your configurations?

FYI: The sandbox works or me both master and 1.x branch.

**Comment by nicosomb** [comment]
I just git cloned the project and tried to install it. No changes.

**Comment by makasim** [comment]
branch?

**Comment by nicosomb** [comment]
> I use master branch. 

;-)

**Comment by makasim** [comment]
You may need to upgrade deps, and add `@dev` to payum-bundle and\or payum

**Comment by makasim** [comment]
Since sandbox master branch require payum-bundle 2.x version but it has not been released yet.

**Comment by alborq** [comment]
Same bug. try today with :

**Comment by alborq** [comment]
<?php             paypal_express_checkout_nvp:
#                factory: paypal_express_checkout
                username:  %paypal_username%
                password:  %paypal_password%
                signature: %paypal_signature%
                sandbox: true

**Comment by makasim** [comment]
@alborq what is wrong with the code?

**Comment by makasim** [comment]
sandbox is not something to be used extensively by others. The main intention to have it is to test everything before releasing stable release. Of course you may use it for some inspirations but it may be unstable, I dont care about it much.

**Comment by alborq** [comment]
makasim 
A problem is here. i have follow this : https://github.com/Payum/PayumBundle/blob/master/Resources/doc/get_it_started.md 

in it, you require the lastest soo v1.2.X 

With it: they say use this conf : 
`    gateways:
        offline:
            factory: offline`

it's a doc. 
this fail with error paste on top. 

i have discover the good way. before, my second message. i dont know if the doc or code is not up to date but, this getting started fail install

**Comment by makasim** [comment]
fixed in https://github.com/makasim/PayumBundleSandbox/commit/21b660deecedb44bec5d7e13bd7a9b675e0237cd
