### ISSUE TITLE
Sandbox does not work with app/console server:run

### ISSUE THREAD

**Issue by davidfuhr** [makasim/PayumBundleSandbox#62]
Due to the changes from 56e4c5cc9edcddd894d237efbd5a45fefaa5e767 the sandbox expects the server variables `SYMFONY_ENV` and `SYMFONY_DEBUG` to be set.

Is there a way to use it to run with `app/console server:run`

Also this does not match the instructions in the readme to use index.php instead of app_dev.php (https://github.com/makasim/PayumBundleSandbox/blob/master/README.md#3-browsing-the-demo-application)

**Comment by makasim** [comment]
this should work: `SYMFONY_ENV=dev SYMFONY_DEBUG=1 app/console server:run`

**Comment by makasim** [comment]
> Also this does not match the instructions in the readme to use index.php instead of app_dev.php 

Yes I know. The README comes from the symfony-standard edition but I personally prefer envs, haven't had change to upgrade the doc.
