### ISSUE TITLE
Paypal Express Checkout - JMS

### ISSUE THREAD

**Issue by thiphamyp** [makasim/PayumBundleSandbox#72]
I am trying to test Paypal Express Checkout - JMS on http://sandbox.payum.org/other/prepare_paypal_via_jms_plugin
This error is displayed: 
"Cannot find right api supported by Payum\Bridge\JMSPayment\Action\CaptureAction"

Could you take a look please?

**Comment by makasim** [comment]
@thiphamyp It worked a long time ago but I haven't tested it for months. Could be broken. 
I'll try to fix it on weekends.

**Comment by makasim** [comment]
Fixed in 1.2.1 version. Make sure you have payum bundle >=2.0 

Changes: https://github.com/Payum/JMSPaymentBridge/commit/ed9ec56a8fb1d17bb8e1a28037dc20842db4a36b
