### ISSUE TITLE
Remove the use of development versions of Payum and PayumBundle

### ISSUE THREAD

**Issue by Aerendir** [makasim/PayumBundleSandbox#73]
Using the development versions cause some errors on database creation and the application is unusable.

**Comment by makasim** [comment]
I use the sandbox to test new versions of payum before release, for that I need a `@dev` version there. to make sure I can install them.

**Comment by Aerendir** [comment]
Ok... I think that the sandbox is a very useful tool for novices that have never used the library before to understand how does it work.

The problem is that if they download the `@dev` version the possible errors may confuse them.
As you told you use the bundle to test the new versions of the library, may be you can leave the stable releases as defaults and, when you are using the bundle for testing purposes, change the requirements to the development version. This way, who downloads the sandbox for the first time has the possibility to fully test a fully working environment.

Another possibility is to explain this choice in the `README.md`, telling that the dependencies requirements are `development` and that, to have a fully working sandbox is required to change the stability level to `@stable`.

A good compromise for me, what do you think about?

**Comment by makasim** [comment]
In the commit https://github.com/Aerendir/PayumBundleSandbox/commit/b8417b888020117573a48e175dbafdd6d391699e you said: `Using the development versions cause an error on database creation. Using stable versions the error disappear and all works.`

What was the error?

**Comment by Aerendir** [comment]
Ooo, i don't remember which it was: that was the very first time I used the bundle and were a lot confused about what I had to expect and how it works...

Unfortunately I also don't know if it were caused by the bundle itself or by the old symfony version. After the upgrade of the entire sandbox to the latest stable version of symfony 2 I didn't try to use again the development versions.

In the end, understanding what you are trying to know, I think that if it is possible to guarantee no errors during the development, then there is no problem to leave the dev version of the dependency; but, if for whatever reason this is not possible, a good idea could be to explain the end user what to expect: I had some difficulties in the beginning. As this is really a very great library/bundle, put a similar "barrier" on the learning curve is useless. IMHO.

**Comment by makasim** [comment]
now. it uses stable version. btw I removed `*` from composer.json.

**Comment by makasim** [comment]
Lots of stuff does not work with any possible version but only with some specific versions. 
So the `*` does not work all the time

**Comment by Aerendir** [comment]
Ok, it's correct and more stable this way :)
