### ISSUE TITLE
Why there are both Payment and PaymentDetails?

### ISSUE THREAD

**Issue by Aerendir** [makasim/PayumBundleSandbox#79]
I'm looking into the bundle and seen that there are two different entities: `Acme\PaymentBundle\Entity\PaymentDetails` and `Acme\PaymentBundle\Entity\Payment`.

Is there a reason for this or is only something to fix?

I think this is linked to the issue on PayumBundle [#388](https://github.com/Payum/PayumBundle/issues/388).

Can you give me some advice about this so I can fix and make them omogeneous? It is now very confusing!

**Comment by makasim** [comment]
Let's talk about it in bundle's issue.
