### ISSUE TITLE
The environment is not set correctly: why?

### ISSUE THREAD

**Issue by Aerendir** [makasim/PayumBundleSandbox#80]
@makasim , In my previous PR #75 , I updated all the sandbox to Symfony 2.8.11 and once the server were started with a simple `app/console server:start` all worked well.

Now, if do the same thing, I receive an error:

> Internal error. The environment is not configured correctly. Please set SYMFONY_ENV and SYMFONY_DEBUG.

Why? It is really necessary to make the developer choose in which environment he wants to run the app?

I've also edited the `README.md` file telling that a simple `app/console server:start` is sufficient to run the app, but it is not correct now.

So, I think a decision is required: make the developer necessary choose in which environment start the app (and editing the `README.md` accordingly) or, make the app run again in the default `dev` environment (leaving the `READDME.md` as now is).

**Comment by makasim** [comment]
There is not anything like that, everything as symfony does

**Comment by makasim** [comment]
FYI: I've not used `app/console server:start` command but standard nginx configuration works fine

**Comment by Aerendir** [comment]
Yes, it is my fork that is not updated, is a fault of mine, not yours. Excuse me!
